name: Fast API
run.name: ${{github.actor}} is running FastAPI
on: [push]
jobs:
  Run-FastAPI-Actions:
    runs-on: ubuntu-latest
    steps:
      -run: echo "The job was automatically triggered by a ${{github.event_name}} event"
      -run: echo "Running on ${{runner.os}} server hosted by github"
      -name: Check out repository code
        uses: actions/checkout@v4
      -run: "github.repository" repository has been cloned to the runner"
      -run: pip install requirements.txt
      -run: uvicorn main:app
