name: Build and deploy Fast API
on: 
  push:
    branches: 
      - main
jobs:
  Build-and-deploy-Fast-API:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
        
   
    - name: Pip Installer
      # You may pin to the exact commit or the version.
      # uses: BSFishy/pip-action@8f2d471d809dc20b6ada98c91910b6ae6243f318
      uses: BSFishy/pip-action@v1
      with:        
        # A requirements file to install from
        requirements: requirements.txt
        # A constraints file to use
    - name: Run fastapi app using uvicorn server
      run: uvicorn main:app --host 0.0.0.0 --port 8000
        
          

               
          
    
