name: Build and deploy Fast API
on: 
  push:
    branches: 
      - main
jobs:
  Build-and-deploy-Fast-API:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
        
   
    - uses: brettcannon/pip-secure-install@v1.0.0
      with:
        # Command to run Python
        python: '3.10'
          # Path to a requirements file
        requirements-file: requirements.txt

               
          
    
